### ISSUE TITLE
Add custom class to close button

### ISSUE THREAD

**Issue by temi4** [a-kalinin/toast-me#13]
Привет. 

1) можешь добавить параметр в options для кнопки закрытия, чтобы ставился кастомный класс?
2) Можно как то убрать? Чтобы использовать только свои стили?
`import styles from './index.scss';`

**Comment by a-kalinin** [comment]
Привет

1) Устанавливается в свойствах action объекта, не хочу добавлять в options, чтобы избежать лишних коллизий. Если появится высокий спрос на такую фичу, тогда подумаю еще.
https://github.com/a-kalinin/toast-me#use-with-own-customization-and-action-button

2) Там где-то полтора десятка классов, вынести в options сейчас времени нет, если согласен ждать - потом могу сделать (переоткрой это ишью). Могу пока порекомендовать перегрузить стили своими через: 
```
    toastClass,
    removedToastClass,
    containerClass,
```
https://github.com/a-kalinin/toast-me#accepted-options
