### ISSUE TITLE
Releases >1.4.8 broken

### ISSUE THREAD

**Issue by TV-T** [a-kalinin/toast-me#47]
Hello,

I was updating my project dependencies and noticed that when upgrading from 1.4.8 to 1.4.13 `toast-me` could no longer be resolved.
It seems that `/lib/toast-me.min.js` is missing from the package entirely. It looks like 

I investigated a little and I think there is an issue in how you publish this package. Your `publish-npm` job doesn't actually build the package. It wasn't failing noticeably previously because you had an old version of the minified build checked into version control, but it was removed [here](https://github.com/a-kalinin/toast-me/commit/b27444a3da3a83814d3fdb02b6a4f0a174200f1b).

Thanks for the wonderful library, we have been using this for about two years now!

**Comment by a-kalinin** [comment]
@TV-T
Hi! Thanks a lot! I received your pull request and will check it this weekend.
