### ISSUE TITLE
Access to Container or control z-index

### ISSUE THREAD

**Issue by nitsujri** [a-kalinin/toast-me#5]
Hi a-kalinin,

Any recommendation on how to set the container class's `z-index`?

I'm looking to use this in response to a bootstrap modal action and the toast appears behind the modal. 

I can get the toast to appear above the modal if I modify the `container` class manually, so I set out to figure how to do that in the library, but was not able to see a way.

Thoughts?

Thanks again!
Justin

**Comment by a-kalinin** [comment]
Hi Justin,
At the moment there is no proper way and I can confirm this issue.
Right now you can use styling through JS:
```
import { ToastMeClass } from 'toast-me';

const options = { // position and type should match options you use for toast
  position = 'top',
  type = 'over',
};
const toastContainer = ToastMeClass.getContainer(options);
toastContainer.style.zIndex = '10';
```
Source code of function is here https://github.com/a-kalinin/toast-me/blob/master/src/toastMe.js , line 9

But this is just a temporary hack.
I will push update in nearest time (1-2 days), to add possibility for set it up with CSS class through options object.

**Comment by nitsujri** [comment]
Perfect that was it. Thanks!

**Comment by a-kalinin** [comment]
New version 1.3.0 published.

* Added new options: `containerClass`, `useUniqueContainer`
* Added some unit-tests
* Upgraded dependencies

For more info check Readme.
Thank you for found issue!

**Comment by nitsujri** [comment]
pulled in - works great thanks so much!

**Comment by a-kalinin** [comment]
You are welcome!
